name: Deploy to EC2

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.CREATIVEGLU_STG_SSH_KEY }}

    - name: Deploy to EC2
      env:
        CREATIVEGLU_MCP: ${{ vars.CREATIVEGLU_MCP_STG_ENV }}
        APP_DIR: /var/www/app/creativecglu-mcp-service
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-170-240-97.compute-1.amazonaws.com 'bash -se' << EOF
          set -euo pipefail
          export APP_DIR="$APP_DIR"
          export CREATIVEGLU_MCP="$CREATIVEGLU_MCP"
          echo "\$CREATIVEGLU_MCP" | base64 -d > \$APP_DIR/.env
          cd \$APP_DIR
          git fetch --depth=1 origin staging
          git reset --hard origin/staging
          npm ci
          npm run build
          pm2 reload all --update-env
          npm run migrate:up
        EOF